#启动端口
server:
  port: 8888

#mybatis
mybatis:
  # 配置此处内容是为了告诉MyBatis mapper文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 配置Mybatis的别名处理器
  type-aliases-package: com.javaclimb.itmusic.pojo.domain
  # 配置Mybatis的驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true

#JDBC
spring:

#  mysql
  datasource:
    url: jdbc:mysql://localhost:3306/itMusic_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 183532
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  .jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

#redis
  redis:
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
    database: 0


#文件上传
servlet:
  multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: D://file/upload/
